#include "stdio.h"

#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "LED.h"
#include "GPIO_Interface.h"
#include "GPIO_Private.h"

HAL_LEDS_INIT()
{
    MCAL_GPIO_INIT(PortF,GPIO_PORTF);
    MCAL_GPIO_SetPinMode(GPIO_PORTF,RED,GPIO_PIN_OUTPUT,GPIO_INPUT_PULL_DOWN_MOD);
    MCAL_GPIO_SetPinMode(GPIO_PORTF,Blue,GPIO_PIN_OUTPUT,GPIO_INPUT_PULL_DOWN_MOD);
    MCAL_GPIO_SetPinMode(GPIO_PORTF,GREEN,GPIO_PIN_OUTPUT,GPIO_INPUT_PULL_DOWN_MOD);
}
HAL_LED_SET(LED_COLOR Color)
{

MCAL_GPIO_SetPinValue(GPIO_PORTF,Color,GPIO_HIGH);
}
HAL_LED_RESET(LED_COLOR Color)
{
MCAL_GPIO_SetPinValue(GPIO_PORTF,Color,GPIO_LOW);
}

HAL_LED_TOGGLE(LED_COLOR Color)
{ u8 x=2;
MCAL_GPIO_GetPinValue(GPIO_PORTF,Color,&x);
x^=1;
MCAL_GPIO_SetPinValue(GPIO_PORTF,Color,x);

}